FROM debian:11-slim

LABEL org.opencontainers.image.authors="https://github.com/ksobrenat32" \
    description="A container image that contains full openjdk-17, rcon, and script for starting a minecraft server"

# Enviroment variables
ENV XMX=1024M
ENV XMS=1024M
ENV SERVER_JAR=server.jar
ENV SERVER_TYPE=VANILLA
ENV SERVER_VERSION=LATEST

# Export ports
EXPOSE 25565
EXPOSE 19132/udp
EXPOSE 19133/udp

# Working dir
VOLUME ["/data"]
WORKDIR /data

# Install java and curl
RUN apt-get update -y && \
    apt-get install -y openjdk-17-jre curl jq && \
    rm -rf /var/lib/apt/lists/*

# Download rcon
RUN mkdir -p /tmp/mcrcon && \
    curl -fsSL -o /tmp/mcrcon/mcrcon.tar.gz $(curl -s https://api.github.com/repos/Tiiffi/mcrcon/releases/latest | grep "browser_download_url.*64.tar.gz" | cut -d : -f 2,3 | tr -d \") && \
    tar -xf /tmp/mcrcon/mcrcon.tar.gz --directory=/tmp/mcrcon && \
    mv /tmp/mcrcon/mcrcon /usr/local/bin/ && \
    ln -s /usr/local/bin/mcrcon /mcrcon && \
    rm -rf /tmp/mcrcon

# Copy Geyser config in case it is needed
RUN mkdir -p /opt/mc/Geyser
COPY ./minecraft/GeyserConfig.yml /opt/mc/Geyser/config.yml

# Entrypoint
COPY ./minecraft/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
