ARG FEDORA_VERSION=43

FROM registry.fedoraproject.org/fedora:${FEDORA_VERSION} AS build-env

ARG FEDORA_VERSION

RUN dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm && \
    dnf -y --setopt=install_weak_deps=false --nodocs \
        --installroot /output --releasever ${FEDORA_VERSION} --use-host-config \
        install glibc coreutils-single prename ffmpeg findutils gawk libva libva-intel-driver && \
    dnf -y --installroot /output --releasever ${FEDORA_VERSION} clean all && \
    rm -rf /output/var/cache/dnf

FROM scratch

LABEL org.opencontainers.image.authors="https://github.com/ksobrenat32" \
    description="A container image that moves movies and removes the title metadata"

COPY --from=build-env /output /
COPY ./entrypoint.sh /entrypoint.sh
COPY ./manual.sh /manual.sh

VOLUME ["/origin"]
VOLUME ["/destiny"]

WORKDIR /origin

ENTRYPOINT [ "/entrypoint.sh" ]
