FROM registry.fedoraproject.org/fedora:38 as build-env

RUN dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm && \
    dnf -y --setopt=install_weak_deps=false --nodocs \
        --installroot /output --releasever 38 \
        install glibc coreutils-single prename ffmpeg inotify-tools && \
    dnf -y --installroot /output --releasever 38 clean all && \
    rm -rf /output/var/cache/dnf

FROM scratch

LABEL org.opencontainers.image.authors="https://github.com/ksobrenat32" \
    description="A container image that moves movies and removes the title metadata"

COPY --from=build-env /output /
COPY ./entrypoint.sh /entrypoint.sh
COPY ./manual.sh /manual.sh

VOLUME ["/origin"]
VOLUME ["/destiny"]

WORKDIR /origin

ENTRYPOINT [ "/entrypoint.sh" ]
