name: Publish Container Image - udns

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: udns
  CONTAINER_DIR: dns

jobs:
  pushGitHubReg:
    name: Push to Github Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build x86_64 image
        run: docker build . --file ./${CONTAINER_DIR}/Containerfile --tag image

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build arm64 image
        run: docker buildx build . --file ./${CONTAINER_DIR}/Containerfile.aarch64 --tag image --platform=linux/arm64

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.actor }}/$IMAGE_NAME
          VERSION=latest
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
